#!/usr/bin/env bash

. ./_scripts/transcript.sh ; transcript_boot_init "$0" || exit 1

. ./set_vars.sh

transcript_boot_ready "$?" || exit 1
transcript_start

echo -e "${RED}[Worker $THISNODE] Restart $CONTAINER_RUNTIME and kubelet$NC\n"

#@ Ensure container runtime and kubelet are enabled/running
systemctl is-active $CONTAINER_RUNTIME --quiet || \
   systemctl restart $CONTAINER_RUNTIME #@ if not already active
systemctl is-enabled kubelet --quiet || \
   systemctl enable kubelet #@ if not already enabled
systemctl is-active kubelet --quiet || \
   systemctl restart kubelet #@ if not already active

echo -e "${RED}[Worker $THISNODE] Remove old joincluster.sh script$NC\n"

#@ Remove any stale join command before fetching a fresh one
rm -f /joincluster.sh /tmp/joincluster.sh #@

##sshpass -p "kubeadmin" scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no kmaster.example.com:/joincluster.sh /joincluster.sh 2>/dev/null
#sshpass -p "kubeadmin" scp -o StrictHostKeyChecking=no kmaster:/joincluster.sh /joincluster.sh

#for n in $NODES ; do
#sshpass -p $KPASS rsync -Ptu --ignore-missing-args -e "ssh -o StrictHostKeyChecking=no" $KUSER@$n:/tmp/joincluster.sh /joincluster.sh
##sshpass -p "kubeadmin" scp -p -o StrictHostKeyChecking=no $KUSER@$n:/tmp/joincluster.sh /joincluster.sh ;
#done

echo -e "${RED}[Worker] Get newest joincluster.sh script from other nodes$NC"

# This script runs on the node, not the client -- no bash ssh function (as defined in set_env.sh) here.
# RSYNC_RSH carries the ssh options for rsync (equivalent to `rsync ... -e "ssh $SSHOPTS" ... ` ).
#@ Fetch the latest kubeadm join command generated by the master
export SSHOPTS="-F ${PWD}/xhosts_ssh_config" #@
export RSYNC_RSH="ssh $SSHOPTS" #@

for n in $NODES ; do
if [[ $n != "$THISNODE" ]]; then
# root can ssh/rsync to master because xhosts_ssh_config carries the key; --ignore-missing-args is intentional
rsync -Ptu --ignore-missing-args "$n:/tmp/joincluster.sh" /tmp/joincluster.sh || true #@ fetch /tmp/joincluster.sh from each other node
fi
done

# cp can fail if no node had joincluster.sh; the check below gives the readable error
cp -puf /tmp/joincluster.sh /joincluster.sh || true #@

# Join worker nodes to the Kubernetes cluster
echo -e "\n${RED}[Worker $THISNODE] Joining node to Kubernetes Cluster$NC"

# joincluster.sh should have been fetched from the master (where boot_master.sh puts it in /tmp);
# if missing here, either the master was not booted yet, boot_master.sh failed, or rsync found nothing
if [ ! -r /joincluster.sh ]; then
   echo -e "${BOLDRED}no file /joincluster.sh, exiting${NC}" >&2
   exit 1
fi
#@ Add this worker's node name to the join command stored in /joincluster.sh
sed -e 's/$/--node-name '$THISNODE'/' -i /joincluster.sh #@
#@ Join this worker to the Kubernetes cluster
if ! bash /joincluster.sh; then #@
   echo -e "${BOLDRED}error running /joincluster.sh, exiting${NC}" >&2
   echo -e "${RED}hint: join tokens expire after 24h — if the master was booted long ago, re-run boot_master.sh to get a fresh token${NC}" >&2
   exit 1
fi

MASTER=$(cut -d' ' -f3 /joincluster.sh | cut -d':' -f1)

#@ Worker joined. From the master, verify node registration:
#@ kubectl get nodes
#@ kubelet config: /var/lib/kubelet/config.yaml
#@ kubelet flags:  /var/lib/kubelet/kubeadm-flags.env

echo -e "${RED}Il worker $THISNODE si e\` unito al cluster$NC"
echo -e "${RED}kubeadm partito su $THISNODE con configurazione 'kubectl -n kube-system get configmaps kubeadm-config -o yaml'$NC"
echo -e "${RED}kubelet partito su $THISNODE con configurazioni /var/lib/kubelet/config.yaml /var/lib/kubelet/kubeadm-flags.env$NC"
echo
echo -e "${RED}Adesso, da qualunque nodo, opera da utente $KUSER (${BOLDRED}NON da super-user)$NC"
echo -e "${RED}e sull'host master (${KNAMES[$MASTER]}, con IP $MASTER) prova:$NC  kubectl get nodes"
